### ISSUE TITLE
Inconsistent casing of storage-module-options.d.ts in published package

### ISSUE THREAD

**Issue by iddan** [codebrewlab/nestjs-storage#3]
The problem only occurs when I'm running the code in Linux (as it is case sensitive by default).
Can you please publish a version to npm with corrected file names of `Storage-module-options.d.ts` and `Storage-module-options.js` in lower cases?
<img width="350" alt="Screenshot 2020-08-16 at 20 19 29" src="https://user-images.githubusercontent.com/12671072/90340023-d155c300-dffd-11ea-8d9c-82d9e0b859b9.png">
<img width="766" alt="Screenshot 2020-08-16 at 20 19 34" src="https://user-images.githubusercontent.com/12671072/90340024-d450b380-dffd-11ea-8373-7252c317bef0.png">

**Comment by tienne** [comment]
Korea is a holiday until today, so we just confirmed the issue.
The pull request you uploaded was distributed on npm. Check out version 0.1.4.

**Comment by tienne** [comment]
@iddan Is it okay to end this issue?

**Comment by iddan** [comment]
Yes, thank you @tienne
