### ISSUE TITLE
 [ExceptionsHandler] Driver gcs is not supported

### ISSUE THREAD

**Issue by gcamrit** [codebrewlab/nestjs-storage#5]
I am having issue reading `google cloud storage` files

app.module.ts
```js
StorageModule.forRootAsync({
  useFactory: () => ({
  default: 'documents',
  disks: {
    documents: {
      driver: DriverType.GCS,
      config: {
        bucket: process.env.GCS_BUCKET,
      },
    },
  },
  })
}),
```

when i try to use `storage service` and `getSignedUrl` i get driver gcs is not supported error 
```js
this.storageService.getDisk('documents').getSignedUrl(image.url)
```

**Comment by tienne** [comment]
Did you set the `keyfilename`?

**Comment by tienne** [comment]
gcs must also be installed with the package below.
@slynova/flydrive-gcs
[see](https://github.com/Slynova-Org/flydrive#registering-external-driver)

**Comment by gcamrit** [comment]
i have already installed `@slynova/flydrive-gcs` package and provided key file name via env like `GOOGLE_APPLICATION_CREDENTIALS=./gcloud.json`

**Comment by gcamrit** [comment]
@tienne Do i need to register gcs driver somewhere ?

**Comment by tienne** [comment]
Yes 
As shown in the example below, you must register using the registerDriver method first.
```typescript
this.storage.registerDriver('s3', AmazonWebServicesS3Storage);
```

Sorry, I wrote the wrong example

**Comment by gcamrit** [comment]
where do i put the registration code on app.module.ts ?

**Comment by tienne** [comment]
I am using the service registered as below.

```Typescript
// image-storage.service.ts
@Injectable()
export class ImageStorageService {
  private readonly disk: AmazonWebServicesS3Storage;

  constructor(private storage: StorageService) {
    if (this.disk === undefined) {
      this.storage.registerDriver('s3', AmazonWebServicesS3Storage);
      this.disk = this.storage.getDisk<AmazonWebServicesS3Storage>();
    }
  }

//...
}

```

**Comment by tienne** [comment]
Is this issue resolved by any chance?
@gcamrit

**Comment by gcamrit** [comment]
Yup thanks for the help
